name: build-linux
on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Prepare for build
      shell: bash --login {0}
      run: |
        sudo apt install -y build-essential gcc
    - name: Compile
      shell: bash --login {0}
      run: |
        make
        chmod +x bin/buildup-editor
    - uses: actions/upload-artifact@v2
      with:
        name: buildup-editor-Linux-x86_64
        path: bin/buildup-editor