name: build-linux-arm64
on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pguyot/arm-runner-action@v2
      with:
        base_image: raspbian_lite:2020-02-13
        commands: |
          ls
    - name: Prepare for build
      run: |
        sudo apt-get install -y libx11-xcb-dev
    - name: Do build
      run: |
        make
